# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('store_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.IntegerField(choices=[(1, 'simples'), (2, 'CRITICA')], verbose_name='Tipo')),
                ('message', models.TextField(default='')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App')),
            ],
            options={
                'ordering': ('-version_code',),
                'verbose_name_plural': 'vers\xf5es',
            },
        ),
    ]
