# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='store_url',
            new_name='app_package',
        ),
    ]
