# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161018_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_package',
            new_name='package',
        ),
    ]
