# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161018_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
